### PR TITLE
[feature] optional printf format specifier

### PR DESCRIPTION
**Pull request by WnP**
hope this help, for me it's useful

### CODE REVIEW

**Comment by andradei** [comment]
This is very useful! Hope it passes all tests and the conflicts are resolved!

**Comment by WnP** [comment]
@andradei done ;)
@jeremyschlatter readme needs to be updated, by the way I don't know if help message modifications are good, english is not my natural language, let me know your through about it and I'll fix it

**Comment by andradei** [comment]
+1 For merging this.

**Comment by WnP** [comment]
Closing this because project is deprecated

**Pull request closed without merging**
